source 'https://rubygems.org'
ruby '2.2.0'
gem 'sinatra', '~> 1.4'
gem 'haml', '~> 4.0'
gem 'json', '~> 1.8'
gem 'rest-client', '~> 1.7'
gem 'uuid', '~> 2.3'
gem 'omniauth-google-oauth2', '~> 0.2'
gem 'puma', '~> 2.11'
gem "sinatra-cross_origin", "~> 0.3"